# Generated by Django 4.2.7 on 2024-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculation_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('years', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
