# Generated by Django 4.2.7 on 2024-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation_database',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
